name: build

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.9.0

      - name: Run tests and extract coverage
        run: |
          go test -timeout=60s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp ./...
          cat $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "mock_" > $GITHUB_WORKSPACE/profile.cov
        env:
          CGO_ENABLED: 0

      - name: Submit coverage to codecov
        run: |
          cat $GITHUB_WORKSPACE/profile.cov > $GITHUB_WORKSPACE/coverage.txt
          cd $GITHUB_WORKSPACE
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GOFLAGS: "-mod=mod"
          CGO_ENABLED: 0

      - name: set up QEMU
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
        uses: docker/setup-qemu-action@v1

      - name: set up Docker Buildx
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
        uses: docker/setup-buildx-action@v1

      - name: login to ghcr
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: login to dockerhub
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v1
        with:
          username: semior
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push master image to ghcr.io
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v5
        timeout-minutes: 30
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ghcr.io/semior001/remapjson:latest,ghcr.io/semior001/remapjson:${{github.sha}}

      - name: build and push master image to dockerhub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v5
        timeout-minutes: 30
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: semior/remapjson:latest,semior/remapjson:${{github.sha}}

      - name: build and push tagged (latest) image to ghcr.io
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/build-push-action@v5
        timeout-minutes: 30
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ghcr.io/semior001/remapjson:latest,ghcr.io/semior001/remapjson:${{github.sha}}

      - name: build and push tagged (latest) image to dockerhub
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        id: docker_build
        uses: docker/build-push-action@v5
        timeout-minutes: 30
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: semior/remapjson:latest,semior/remapjson:${{github.sha}}
